#
# Copyright (c) 2020 Yao Wei Tjong. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

name: Compiler toolchains builder

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  rpi:
    name: Raspberry Pi
    runs-on: ubuntu-latest
    env: 
      CONFIGS: aarch64-rpi3-linux-gnu.config armv8-rpi3-linux-gnueabihf.config armv7-rpi2-linux-gnueabihf.config armv6-rpi-linux-gnueabi.config
      TAG_NAME: weitjong/toolchains-rpi
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: docker build --build-arg CONFIGS='${{ env.CONFIGS }}' -t ${{ env.TAG_NAME}} .

# vi: set ts=2 sw=2 expandtab:
